#!/usr/bin/env python3
"""
privacy_check.py - refuse to publish anything carrying personal detail.

    python privacy_check.py          exits non-zero if anything is found

Run this before every push. It scans only the files git would actually commit,
because that is the set that becomes permanent and public.

This repository was built clean rather than sanitised: no document, name, figure
or path from any real matter has ever been in it, and the sample documents are
generated by a script so anyone can verify they are invented. This check exists
anyway, because "I was careful" is not a measurement and a repository is forever.

Same rule as the coverage gate it sits beside: a check only counts if a tool
produced the number.
"""
import re
import subprocess
import sys

# The terms themselves live OUTSIDE the repository, in .private-terms, which is
# gitignored. That is not fussiness: an earlier version of this file hard-coded
# the list, and the check failed on itself. A script that publishes the names it
# is protecting is worse than no script at all. It caught its own leak, which is
# the only reason you can trust it caught anything else.
TERMS_FILE = ".private-terms"

# His own name belongs in a copyright line and nowhere else.
ALLOW = {"LICENSE"}


def load_terms():
    try:
        with open(TERMS_FILE, encoding="utf-8") as f:
            terms = [ln.strip() for ln in f
                     if ln.strip() and not ln.lstrip().startswith("#")]
    except FileNotFoundError:
        sys.exit(f"no {TERMS_FILE}. Copy .private-terms.example and fill it in "
                 f"with the names, places and identifiers that must never ship.")
    if not terms:
        sys.exit(f"{TERMS_FILE} is empty. An empty gate always passes, which is "
                 f"the same as having no gate.")
    return re.compile("|".join(re.escape(t) for t in terms), re.I), len(terms)


def tracked_files():
    r = subprocess.run(["git", "diff", "--cached", "--name-only"],
                       capture_output=True, text=True)
    files = [f for f in r.stdout.split() if f]
    if not files:
        r = subprocess.run(["git", "ls-files"], capture_output=True, text=True)
        files = [f for f in r.stdout.split() if f]
    return files


def main():
    pattern, n_terms = load_terms()
    files = tracked_files()
    if not files:
        sys.exit("nothing staged or tracked. Run `git add -A` first.")

    hits = []
    for f in files:
        if f in ALLOW:
            continue
        try:
            with open(f, encoding="utf-8", errors="replace") as fh:
                for i, line in enumerate(fh, 1):
                    m = pattern.search(line)
                    if m:
                        hits.append((f, i, m.group(0), line.strip()[:70]))
        except (IsADirectoryError, PermissionError):
            pass

    print(f"scanned {len(files)} file(s) git would publish\n")
    if hits:
        print(f"FAILED. {len(hits)} match(es). Do NOT push.\n")
        for f, i, term, line in hits:
            print(f"  {f}:{i}  [{term}]  {line}")
        sys.exit(1)
    print("PASSED. No names, matter numbers, locations or contact details.")
    print("Note: this checks what a pattern can see. Read the diff yourself too.")


if __name__ == "__main__":
    main()
